# Generated by Django 4.2.14 on 2024-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AlterField(
            model_name="orders",
            name="city",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AlterField(
            model_name="orders",
            name="email",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AlterField(
            model_name="orders",
            name="items_json",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="orders",
            name="name",
            field=models.CharField(default="", max_length=90),
        ),
        migrations.AlterField(
            model_name="orders",
            name="pincode",
            field=models.CharField(default="", max_length=111),
        ),
        migrations.AlterField(
            model_name="orders",
            name="state",
            field=models.CharField(default="", max_length=111),
        ),
    ]
